#!/bin/sh
#Written by Wang Shilong <wangshilong1991@gmail.com>

MAIN_URL="https://patchwork.kernel.org/project/LKML/list/"
PATCH_URL="https://patchwork.kernel.org/patch/"
LOG_DIR="/tmp/auto_check"
LOG_INDEX="/var/log"
TIME_OUT=60
IGNORE_OVER_80_CHARS=1

function check_errors()
{
	summary=`less  "$1" | sed -n '/total:.*errors,.*warnings,.*lines checked/p'`
	if [ -z "$summary" ];then
		echo "$1" > log
		return 0
	fi
	errors=`echo $summary | awk -F ' ' '{print $2}'`
	warnings=`echo $summary | awk -F ' ' '{print $4}'`

	#if errors exist, we must deal with this patch
	if [ $errors -gt 0 ];then
		return 1
	fi
	if [ $IGNORE_OVER_80_CHARS -eq 0 ];then
		return 1
	fi
	#if all the warning are over 80 chars, we can select to ignore it
	cnt_over=`less "$1" | grep "WARNING: line over 80 characters" | wc -l`
	if [ $cnt_over -ge $warnings ];then
		echo "cnt_over: $cnt_over warning: $warnings" >> log
		return 0
	fi
	return 1
}
rm -rf $LOG_DIR
mkdir -p $LOG_DIR || echo "mkdir $LOG_DIR fails"

wget -O $LOG_INDEX/out $MAIN_URL -T $TIME_OUT -t 3 || exit 1
grep '/patch/' $LOG_INDEX/out | awk -F '/' '{print $3}' >$LOG_INDEX/patch_index

touch $LOG_INDEX/send_index
grep -F -v -f $LOG_INDEX/send_index $LOG_INDEX/patch_index | uniq -u >$LOG_INDEX/out1
rm -f $LOG_INDEX/patch_index && mv $LOG_INDEX/out1 $LOG_INDEX/patch_index
rm -f $LOG_INDEX/out || echo "rm $LOG_INDEX/out fails"

while read line
do
	wget $PATCH_URL/$line/mbox -O $LOG_DIR/$line -T $TIME_OUT -t 3 || echo "wget $line fails";
	./checkpatch.pl --no-tree --patch $LOG_DIR/$line || ./checkpatch.pl --no-tree --patch $LOG_DIR/$line >$LOG_DIR/$line""_fail
	echo $line >> $LOG_INDEX/send_index

done < $LOG_INDEX/patch_index

ls $LOG_DIR | grep fail | awk -F '_' '{print $1}' > $LOG_INDEX/check_fail

while read line
do
	#double check whether it is a patch
	#get email from and cc to linux-btrfs
	is_null=`less $LOG_DIR/$line | grep Signed-off-by`
	if [ -z "$is_null" ];then
		continue
	fi
	check_errors $LOG_DIR/$line""_fail && continue

	#There there may be several From: we just pick up first one
	to=`less $LOG_DIR/$line | sed '10q' | grep From: |awk -F ':' '{print $2}'`

	line_start=`less $LOG_DIR/$line | sed 10q | sed -n '/Subject:/='`
	line_end=`less $LOG_DIR/$line | sed 10q | sed -n '/From:/='`
	line_end=$(($line_end-1))
	echo $line_start $line_end >>log
	Subject=`less $LOG_DIR/$line | sed -n "$line_start,$line_end p"| sed 's/Subject://g'`	

	line_start=`less $LOG_DIR/$line | sed 40q | sed -n '/Message-Id:/='`
	line_start=$(($line_start+1))
	line_end=`less $LOG_DIR/$line | sed 40q | sed -n '/Date:/='`
	line_end=$(($line_end-1))

	cc1=`less $LOG_DIR/$line | sed -n "$line_start,$line_end p"| sed 's/To://g' | sed 's/Cc://g'`	
	cc2=",,Wang Shilong <wangshilong1991@gmail.com>"
	cc=${cc1}${cc2}

	#name=`echo $to| awk -F ':' '{print $2}'| awk -F '<' '{print $1}'`

	#generate an email
	rm -rf $LOG_DIR/email

	#echo "Subject:$Subject" >>$LOG_DIR/email
	#echo "To: $to" >>$LOG_DIR/email
	#echo "Cc: $cc" >>$LOG_DIR/email

	head="Hello, Using checkpatch.pl, i get the following warnings(errors):"
	echo $head >>$LOG_DIR/email
	warn=`cat $LOG_DIR/$line""_fail >>$LOG_DIR/email`
	echo $warn >>$LOG_DIR/email
	tail="Thanks, Wang"
	echo $tail >>$LOG_DIR/email
	echo ""    >>$LOG_DIR/email
	echo "Notice: this is an automatically generated by shell script" >>$LOG_DIR/email
	echo "Any problems please contact: wangshilong1991@gmail.com" >>$LOG_DIR/email
	msg=`cat $LOG_DIR/email | sed "s;$LOG_DIR/$line;patch;g"` 
	echo $msg

	#echo $msg
	#to="wangshilong1991@gmail.com"
	#cc=""
	sh /root/tools/auto_check/mail.sh "$to" "$cc" "Re: $Subject" "$msg"
done < $LOG_INDEX/check_fail
